name: Release x86 OCI image

on:
    push:

env:
    REGISTRY: ghcr.io

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v4
            - name: Install docker
              uses: docker-practice/actions-setup-docker@master
            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: build image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: "./docker/Dockerfile"
                  push: true
                  tags: "ghcr.io/eason0729/container-copy:latest"
                  labels: "latest"
